# We have a conf and classes directory, add to BBPATH.
BBPATH .= ":${LAYERDIR}"

# We have recipes in this layer.
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "beagleycluster"
BBFILE_PATTERN_beagleycluster = "^${LAYERDIR}/"
BBFILE_PRIORITY_beagleycluster = "8"

LAYERDEPENDS_beagleycluster = "core"
LAYERSERIES_COMPAT_beagleycluster = "scarthgap"
