SUMMARY = "Beagley boot diagnostics image"

require beagley-cluster-image.bb

BEAGLEY_BOOT_KERNEL_ARGS:beagley-ai = "rw net.ifnames=0 earlycon=ns16550a,mmio32,0x02800000 console=ttyS2,115200n8 console=tty1 loglevel=7 ignore_loglevel systemd.log_level=debug systemd.log_target=console systemd.show_status=1 udev.log_level=debug beagley.diag=1"

do_stage_beagley_diag_extlinux() {
    if [ "${MACHINE}" != "beagley-ai" ]; then
        exit 0
    fi

    install -d "${DEPLOY_DIR_IMAGE}"
    cat >"${DEPLOY_DIR_IMAGE}/extlinux.conf" <<EOF
# Generic Distro Configuration file generated by OpenEmbedded
LABEL Beagley Cluster Diagnostics
	KERNEL /Image
	FDT /dtb/ti/k3-am67a-beagley-ai.dtb
	APPEND root=LABEL=root rootfstype=ext4 ${BEAGLEY_BOOT_KERNEL_ARGS}
EOF
}

addtask do_stage_beagley_diag_extlinux after do_image before do_image_wic
