#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HOST="${BEAGLEY_HOST:-root@beagley-ai.local}"
DURATION_SECONDS=60
WARMUP_SECONDS=20
OUT_DIR="$ROOT/build/perf"
HUB_URL="${VEHICLE_HUB_WS_URL:-ws://10.24.0.7:8765}"
EFFECT_LEVEL="${BEAGLEY_EFFECT_LEVEL:-high}"
RENDER_LOOP="${QSG_RENDER_LOOP:-auto}"
MIN_FPS=45
MAX_P95=35
MAX_P99=60
RESTORE_AFTER=0

usage() {
  cat <<'EOF'
Usage:
  tools/perf/run_beagley_real_world_fps.sh [options]

Runs the live BeagleY systemd service on the HDMI display with real native
online maps, perf logging, no replay file, and no stress scene. The current
/etc/default/beagley-cluster.local is backed up on the BeagleY before changes.

Options:
  --host HOST             SSH target. Default: root@beagley-ai.local
  --duration SECONDS      Measured sample duration after warmup. Default: 60
  --warmup SECONDS        Warmup time before measuring. Default: 20
  --out-dir DIR           Local output directory. Default: build/perf
  --hub-url URL           Vehicle hub WebSocket URL. Default: ws://10.24.0.7:8765
  --effect-level LEVEL    off, low, or high. Default: high
  --render-loop LOOP      Qt scenegraph render loop. Default: auto
  --min-fps N             Perf check minimum FPS. Default: 45
  --max-p95 MS            Perf check maximum p95 frame time. Default: 35
  --max-p99 MS            Perf check maximum p99 frame time. Default: 60
  --restore               Restore the previous BeagleY local env after capture.
  -h, --help              Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host)
      HOST="${2:-}"
      shift 2
      ;;
    --duration)
      DURATION_SECONDS="${2:-}"
      shift 2
      ;;
    --warmup)
      WARMUP_SECONDS="${2:-}"
      shift 2
      ;;
    --out-dir)
      OUT_DIR="${2:-}"
      shift 2
      ;;
    --hub-url)
      HUB_URL="${2:-}"
      shift 2
      ;;
    --effect-level)
      EFFECT_LEVEL="${2:-}"
      shift 2
      ;;
    --render-loop)
      RENDER_LOOP="${2:-}"
      shift 2
      ;;
    --min-fps)
      MIN_FPS="${2:-}"
      shift 2
      ;;
    --max-p95)
      MAX_P95="${2:-}"
      shift 2
      ;;
    --max-p99)
      MAX_P99="${2:-}"
      shift 2
      ;;
    --restore)
      RESTORE_AFTER=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[real-fps] unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

for value in "$HOST" "$HUB_URL" "$EFFECT_LEVEL" "$RENDER_LOOP"; do
  if [[ "$value" == *"'"* ]]; then
    echo "[real-fps] values may not contain single quotes: $value" >&2
    exit 2
  fi
done

STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p "$OUT_DIR"
LOG_FILE="$OUT_DIR/beagley-real-world-fps-$STAMP.log"
SUMMARY_FILE="$OUT_DIR/beagley-real-world-fps-$STAMP.summary.txt"

echo "[real-fps] Step 1: Verify SSH..."
ssh -o BatchMode=yes -o ConnectTimeout=8 -o StrictHostKeyChecking=accept-new "$HOST" true

echo "[real-fps] Step 2: Install real-world perf runtime profile..."
BACKUP_PATH="$(
  ssh "$HOST" "set -e
    perf_dir=/var/lib/beagley-cluster/perf
    local_env=/etc/default/beagley-cluster.local
    backup=\$perf_dir/beagley-cluster.local.before-real-world-fps.$STAMP
    mkdir -p \"\$perf_dir\"
    if [ -f \"\$local_env\" ]; then
      cp \"\$local_env\" \"\$backup\"
    else
      : >\"\$backup\"
    fi
    awk -F= '
      BEGIN {
        drop[\"BEAGLEY_UI_VARIANT\"]=1
        drop[\"BEAGLEY_RENDER_PROFILE\"]=1
        drop[\"BEAGLEY_EFFECT_LEVEL\"]=1
        drop[\"BEAGLEY_GAUGE_DETAIL\"]=1
        drop[\"BEAGLEY_GAUGE_DEMO\"]=1
        drop[\"BEAGLEY_CLUSTER_SIMULATION\"]=1
        drop[\"BEAGLEY_MAP_RENDERER\"]=1
        drop[\"BEAGLEY_MAP_BOOT_MODE\"]=1
        drop[\"BEAGLEY_MAP_STYLE_MODE\"]=1
        drop[\"BEAGLEY_PROFILE_METRICS\"]=1
        drop[\"BEAGLEY_REPLAY_FILE\"]=1
        drop[\"BEAGLEY_REPLAY_LOOP\"]=1
        drop[\"BEAGLEY_STRESS_SCENE\"]=1
        drop[\"QSG_RENDER_LOOP\"]=1
        drop[\"VEHICLE_HUB_WS_URL\"]=1
      }
      /^# Real-world FPS profile generated by tools\/perf\/run_beagley_real_world_fps.sh$/ { next }
      /^[[:space:]]*#/ || /^[[:space:]]*$/ { print; next }
      {
        key=\$1
        sub(/^[[:space:]]*/, \"\", key)
        sub(/[[:space:]]*$/, \"\", key)
        if (!(key in drop)) print
      }
    ' \"\$backup\" >\"\$local_env.tmp\"
    cat >>\"\$local_env.tmp\" <<'REMOTE_ENV'

# Real-world FPS profile generated by tools/perf/run_beagley_real_world_fps.sh
BEAGLEY_UI_VARIANT=v3
BEAGLEY_RENDER_PROFILE=embedded
BEAGLEY_EFFECT_LEVEL=$EFFECT_LEVEL
BEAGLEY_GAUGE_DETAIL=safe
BEAGLEY_GAUGE_DEMO=0
BEAGLEY_CLUSTER_SIMULATION=0
BEAGLEY_MAP_RENDERER=native-online
BEAGLEY_MAP_BOOT_MODE=staged
BEAGLEY_MAP_STYLE_MODE=embedded
BEAGLEY_PROFILE_METRICS=1
BEAGLEY_REPLAY_LOOP=0
BEAGLEY_STRESS_SCENE=0
VEHICLE_HUB_WS_URL=$HUB_URL
REMOTE_ENV
    if [ "$RENDER_LOOP" != "auto" ]; then
      printf 'QSG_RENDER_LOOP=%s\n' "$RENDER_LOOP" >>"\$local_env.tmp"
    fi
    cp \"\$local_env.tmp\" \"\$local_env\"
    chmod 0644 \"\$local_env\"
    rm -f \"\$local_env.tmp\"
    echo \"\$backup\""
)"
echo "[real-fps] Remote env backup: $BACKUP_PATH"

echo "[real-fps] Step 3: Restart beagley_cluster and warm up..."
ssh "$HOST" "systemctl daemon-reload && systemctl reset-failed beagley_cluster && systemctl restart beagley_cluster"
sleep 4
ssh "$HOST" "systemctl show beagley_cluster -p ActiveState -p NRestarts --value"
sleep "$WARMUP_SECONDS"

echo "[real-fps] Step 4: Measure for ${DURATION_SECONDS}s..."
SINCE_EPOCH="$(ssh "$HOST" "date +%s")"
sleep "$DURATION_SECONDS"

echo "[real-fps] Step 5: Pull journal to $LOG_FILE..."
ssh "$HOST" "journalctl -u beagley_cluster --since '@$SINCE_EPOCH' --no-pager" >"$LOG_FILE"

set +e
{
  echo "[real-fps] Log: $LOG_FILE"
  echo "[real-fps] Env backup on BeagleY: $BACKUP_PATH"
  echo
  echo "[real-fps] Runtime evidence:"
  grep -E "\\[BOOT\\]|replay mode enabled|connecting to|handshake accepted|BBB GPS|first valid BBB GPS|GPS ready|socket error|\\[Perf\\]" "$LOG_FILE" | tail -80 || true
  echo
  "$ROOT/tools/perf/check_perf_log.sh" "$LOG_FILE" \
    --min-fps "$MIN_FPS" \
    --max-p95 "$MAX_P95" \
    --max-p99 "$MAX_P99"
} | tee "$SUMMARY_FILE"
CHECK_STATUS="${PIPESTATUS[0]}"
set -e

if [[ "$RESTORE_AFTER" == "1" ]]; then
  echo "[real-fps] Step 6: Restore previous local env..."
  ssh "$HOST" "cp '$BACKUP_PATH' /etc/default/beagley-cluster.local && chmod 0644 /etc/default/beagley-cluster.local && systemctl daemon-reload && systemctl reset-failed beagley_cluster && systemctl restart beagley_cluster"
fi

echo "[real-fps] Summary: $SUMMARY_FILE"
exit "$CHECK_STATUS"
