#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HOST="${BEAGLEY_HOST:-root@beagley-ai.local}"
HUB_URL="${VEHICLE_HUB_WS_URL:-ws://10.24.0.7:8765}"
EFFECT_LEVEL="${BEAGLEY_EFFECT_LEVEL:-high}"
METRICS=0
RESTART=1
HEALTH=1

usage() {
  cat <<'EOF'
Usage:
  tools/ui/beagley_live_cluster_profile.sh [options]

Puts the BeagleY into the live production-like UI path:
- V3 shell on the real BeagleY display
- native-online maps
- live BBB vehicle_state hub
- no BeagleY app replay file
- no BeagleY stress scene

This is the source-of-truth profile for UI work that should match the final
runtime path. Use BBB bench vehicle sim upstream when you need animated gauge
inputs without a road test.

Options:
  --host HOST             SSH target. Default: root@beagley-ai.local
  --hub-url URL           Vehicle hub URL. Default: ws://10.24.0.7:8765
  --effect-level LEVEL    off, low, or high. Default: high
  --metrics               Enable BeagleY perf metrics.
  --no-restart            Write env without restarting.
  --no-health             Skip post-restart health check.
  -h, --help              Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host)
      HOST="${2:-}"
      shift 2
      ;;
    --hub-url)
      HUB_URL="${2:-}"
      shift 2
      ;;
    --effect-level)
      EFFECT_LEVEL="${2:-}"
      shift 2
      ;;
    --metrics)
      METRICS=1
      shift
      ;;
    --no-restart)
      RESTART=0
      shift
      ;;
    --no-health)
      HEALTH=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[beagley-live] unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

for value in "$HOST" "$HUB_URL" "$EFFECT_LEVEL"; do
  if [[ "$value" == *"'"* ]]; then
    echo "[beagley-live] values may not contain single quotes: $value" >&2
    exit 2
  fi
done

STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
echo "[beagley-live] Step 1: Verify SSH..."
ssh -o BatchMode=yes -o ConnectTimeout=8 -o StrictHostKeyChecking=accept-new "$HOST" true

echo "[beagley-live] Step 2: Install live cluster profile..."
BACKUP_PATH="$(
  ssh "$HOST" "set -e
    backup_dir=/var/lib/beagley-cluster/profile-backups
    mkdir -p \"\$backup_dir\"
    backup=\$backup_dir/beagley-cluster.local.before-live-profile.$STAMP
    if [ -f /etc/default/beagley-cluster.local ]; then
      cp /etc/default/beagley-cluster.local \"\$backup\"
    else
      : >\"\$backup\"
    fi
    cat > /etc/default/beagley-cluster.local <<'REMOTE_ENV'
BEAGLEY_TOUCH_USB_RECOVERY=1
BEAGLEY_TOUCH_GATE_TIMEOUT=20
BEAGLEY_REQUIRE_GPU_GATE=1
BEAGLEY_REQUIRE_TOUCH_GATE=0

# Live production-like cluster profile generated by tools/ui/beagley_live_cluster_profile.sh
BEAGLEY_UI_VARIANT=v3
BEAGLEY_RENDER_PROFILE=embedded
BEAGLEY_EFFECT_LEVEL=$EFFECT_LEVEL
BEAGLEY_MAP_RENDERER=native-online
BEAGLEY_MAP_BOOT_MODE=staged
BEAGLEY_MAP_STYLE_MODE=embedded
BEAGLEY_PROFILE_METRICS=$METRICS
BEAGLEY_REPLAY_LOOP=0
BEAGLEY_STRESS_SCENE=0
QSG_RENDER_LOOP=basic
VEHICLE_HUB_WS_URL=$HUB_URL
REMOTE_ENV
    chmod 0644 /etc/default/beagley-cluster.local
    rm -rf /root/.cache/Beagley/BeagleyCluster/qmlcache
    echo \"\$backup\""
)"
echo "[beagley-live] Remote env backup: $BACKUP_PATH"

if [[ "$RESTART" != "1" ]]; then
  echo "[beagley-live] Restart skipped"
  exit 0
fi

echo "[beagley-live] Step 3: Restart beagley_cluster..."
ssh "$HOST" "systemctl daemon-reload && systemctl reset-failed beagley_cluster && systemctl restart beagley_cluster"

if [[ "$HEALTH" != "1" ]]; then
  echo "[beagley-live] Health check skipped"
  exit 0
fi

echo "[beagley-live] Step 4: Health check..."
if ! "$ROOT/skills/beagley-health-check/scripts/check.sh"; then
  echo "[beagley-live] Health check failed; collecting debug output..."
  "$ROOT/skills/beagley-debug-service/scripts/debug.sh" || true
  exit 1
fi

echo "[beagley-live] Complete"
